language: python
python:
- '3.6'
install:
- pip install -r requirements/test.txt
- pip install -e cdi-linking
- pip install -e linking_ext
script:
- pytest cdi-linking/test
after_script: cd ~
after_success:
- coveralls
deploy:
  provider: pypi
  user: novavic
  server: https://testpypi.python.org/pypi
  password:
    secure: RlJg1BfJAWWgQPmN3K/s/Xcq8JWdyzEM21HtWacI4DWvhxW0VVB3dGNPSNQxZ896EFurEgBHCmV9S9qion4qcBAwyvjBSXHsaAfvCcF4EchJ3RAGJrbwMy6si5k2tP07KZpi0aeaO6wrNzw1zVT2cn+ghSE5iigRnoF4xWsC3mE/JdWIhJkh6zretdzdFplFtxzRHHTH85isFbFA/PNwCEeh0xTVrU1GPPeJ6JdrOOBd9mGvOn60XEmKjHfDrlPTge2tuinJNU4OQQUeRGbsy9Mhzdsjytp8tsvOU6NXQN/XoVBG9jFhksvD+602xbfW7uCjPHkZoO2IRGB87LnHUP7N7o58kXDGCzRYIGPpQ2lO9k9IKXE41+A4OEVzveHaH9epgwwe1gI3c5NKg2SniDYR09D75foSYx+/invlMyT7aqD3gGA7Xth9d62Ty8Vd7VFpeTWxqgRKdt6zPlW0CAug+/5vU/w0IoFQkusBVR3kOjHG2Bpwfbg6kLGJOAgnGEpr1Ni8S/S8pLGQM/o8HoTHpGl296ScHOTxFw7gkMJJTA9E9tS/QvbIG68e/PC2rKE5fV7QZLphbiiYrp4yzXtyMxVMRZ1D67Y1ciZFuGAW9xtBZ4grF73HxE599fUSNnGAbKwXYxaFb5OUuZYzDjDeB4mb0obzhTb/PgYqOZ4=
