sudo: required
services:
- docker
language: python
python:
- '3.6'
install:
- pip3 install -r requirements/test.txt
- pip3 install wheel
script:
- python3 setup.py test
env:
  DOCKERHUB_USERNAME:novavic
  global:
    secure: KGp962uHImld/E+h0KJBrv3xMpNrcf12jpSsr9Cq+Q7WGIxkTdQlr6Tk8EgW0S/YeMXa23WnbBUdXOxeAWKyopO0SyAcV2FX+dbuTP2CUn3a4Opl//uL9/1Xuip9zfbRWPANajxSxWLXEiFrkwyShxJ1a44O4m6J+RHcOyQ5q8W2Tc1nQIosua/7PbOvezY9Wzr4XJ0TBExrrg8GRsdU6NbsN+vPCIvNb2wk4gxdfuDmvv4p+nrKJ0HUCfTXHRxsrgCE2Y9pWm643e/huXwv2uTFNBXdmXrt9tXHgVH4HS1XkF12/vTs0UM2ropxYlphL+Jxjr7ThdNfzvSxtgn04mWJQargSzDlVj5oLjjQ4CysL0lFGGnAWiDzevCdf/VJQJAEf2g395WxOtsQWstDCQDDvSNqFBTGSNBad6JdPvpJG7/07N3dCClXetm3bi2Ijbl2Wz9fK93N8bjkjK5gFRKksyGa88WakptYbZANWBowov71aPFgW0QERB4LhKJIeas6ERT5H2l8XGZFbfApkuGkfKKJjQ/rMLV4AcrQPn2pKc/4cXmcvpZGxtwvKOqQse8TkRDIVaEt+DrvCeH4EbjEgN/WwtrxP3pjwITbl7Yr+B1CSKlFWM5n5Qh17b9tkcWf2w1sDJRhLcgRCIOvAiGc2w4d4svKAxPAHV+9Ng4=
deploy:
  provider: script
  script: bash linkage-worker/after_deploy.sh
