sudo: required
language: python
python:
  - '3.6'
services:
  - docker
install:
  - pip3 install -r requirements/test.txt
  - pip3 install wheel
script:
  - python3 setup.py test
  - export LIB_VERSION=$(git describe --always)
  - echo $LIB_VERSION
deploy:
  provider: pypi
  user: Jujaga
  server: https://test.pypi.org/legacy/
  distributions: bdist_wheel
  dist: python
  package_glob: dist/*.whl
  on:
    tags: true
  password:
    secure: FMH+um+F+PF4TYjLKysL6HwcCN1mu83AwYBUoCHjebH64jqoJDQbl5GBlvYiNzp8LjYmPlkpYL1IvGykUBhxFHTYnHUE36zKvYtcc1ElCkVKoVL1vXzlk68cSb1C83YUUmuw5yzHhOnpofPUuMThiSJLXCuhT+NW3JzYfuxvDl0o5EQs/fZlkIK9/YblHMvEQhRwCDBEE3IpNPUsV/hAIHKDoQyLVdsJWzGqbEt1OvyiKHqNq8qPVBbZ1VR0ikYzUQT8OguwAlrlZoH34ws/aTAfI+5OA7f289qTw7CsJDnfKOKLmCAikh4Twh+71m2ZIljaNcwVCDJYemoQbH/seU7+6yjnk5+0cJnA+s1gJayBLqfDLyVMymT0/rin3Q2MH4jniIdeOeHMOV3JKU94k4X9HnCBnm0h0/rV57ZjMs7p7LsC5a4iHxfDBbgOrnRtU1/dERWTfjm7jHoSICsAkvP7IcwQbYrjFZ+Jla1ObC7qj42OhKvwSvcpXvTZZRIp6ZGQQLD3nz9Mw0wSBhj5G4j+18UsKGu84BoAVnXE5EyxKL/Zb4421XnLt5QjZakVu91w28ixdWdw4wzxnvhI/L3Iy2ySImbquyvkqV4Z8P7fKhvajaWLRdVOzLTXX3SdZOBNJ9u/JLXyo3+GznqHIxQ+UFxVc5kfKfaz3dT9CDE=
after_deploy:
  - bash worker/after_deploy.sh
env:
  global:
    - secure: pgzzK9BRpoUzUdjQs6OOOvVFvfVle5YH6Xgxq2Y1u8PLt/4BhsRoeGynhmqn8H8pg0cyixG3+hjoLTNySjzt3ocHi7Sxq16rrbhirgqP95GRh0z87yURQ90y6DemIacWVfn5ugvJFUYrlWKkXMnU6/chuaWGM3QnERJtH803jFGtB4kzGmEuXBVCNwuX535aGP3hpAgu+QjHBQr3oN2ZZLKmftCcgWSxnHVlzTbbuFG5ZNUoXve1CK5IQMgZzWhWlRbZ8A+YQnxuv3W6G/kIJWr0uEe2jy5+8H/f7TKHn6PzMXvkMk85E0bGvueR0P88JQiRP+En7DKo1ArWVaUu80KCgE5jYEerlY0TsDPQ8c9Rv+++teQdu4yMeQpDY98fe+eNgmxyHmomKv23GWbYh6GVrVSI7nVjIjNGpTNjLHiJd2s2+aqbwdhyRgrW6FH85ekyTCStgKZIKZ23Tuxk4K+6OO2t35KLdTWmE6+df+Ms8siKRqISSaGLGavkRGfUWQloDfq3WVHhrbryqK8fcPu2tvHDZG5+UQGJTGfhvSGcPk7OuBDKutRyVoB9gnEiD7z/zMEi0V2Qvd5Bo7fI1iHz9r9Eb3Lm67pab/jmWJkOP2MGZK77gbugR3N2ya+rpSxpqTN8m1g5SV42BRRwySJjn4ZsFoiLN/0U2KlTBLU=
    - secure: WGjwhyHOnfHAgCHe8LFeSgaeCz0dG5IRcDRBm4KPr6uCMOaaDEuCilIC1zryhfZAs+PBNfHwwI/Uki6PFdunLE4TY6YXcTCjM0ZheFWfT52+QMkT1D/QnIbElfp2tqDtTHZrZ9gPZMleEyLeocU3UX4RYYMWBVKRMaHBq5a7Td4GiG1i/HvQ/ODl26spIDwvUaZg835apGfxLcSvJUEDy7chBcnY6+VqeEEmC3L9wkVMwPXY/eS3fDb6lSfu1eo66ieuXTg+7xrZAKQHkm4qcRaX4/gylgeH3/YYDLxxf5ZfuFwkhLfUhhTQ5yoLHn3i9e70llbjaeibPs94/rgbZAcGmNsbNItAI57SolaoQNPnxgcs1VCWbhfvXeG0qJwml1REEhftdqdN+9u5u/4vxck5Yganp6qZWsJ7DgbMnPO5LaXtw047EE/JrodNpvYJFvVcf456ytWfMzaHZ2PrGKvB+mNKypjQDCt3c0tmcHCjBW9UK6RSVyV4gnrPZREl06Ecf9wTCvLz9CD06/jV5S3kydd2KxlWqkW5W+ZKqTB1HzYjx7Hw/oV+g0oY4XNAh1yRg60a0SmkVgo0yTFgMYN0r2Ct3wZN3h9Iz0ldJOXGw3k8UVuzxcFmlk83crA74iMoCkaoa1kEr/MYNYWxjJWPYJkk6Vtlh1P/J/iqyR4=
