language: python
python:
  - "3.6"
install:
  - pip install -r requirements/base.txt
  - pip install -r requirements/test.txt
  - pip install -e linking_ext 
script:
  - pytest cdi-linking/test
after_success:
  - coveralls
