sudo: required
language: python
python:
  - '3.6'
services:
  - docker
install:
  - pip3 install -r requirements/test.txt
  - pip3 install wheel
script:
  - python3 setup.py test
  - export APP_VERSION=$(git describe --always)
  - echo $APP_VERSION   
deploy:
  provider: pypi
  user: novavic
  server: https://test.pypi.org/legacy/
  distributions: bdist_wheel
  dist: python
  package_glob: dist/*.whl
  on:
    tags: true
  password:
    secure: YxQNqaSjDW5F0fa+yymSGMEaN7avlh4X4nyH6glPNxpQVOtW4UQUMdQ+TAc2qAoXaFTp2uMcGubSaxeZzEkzCd2Orj5s9mTHBGlgWl47a7oM6zI1MSkCl0yzXBszLWs7IbAjhb6/0dHxH5aqbWFdk5LkvnE//p99DUYL2GPlkhJUHKa/ER7W0W4Xv97AXWfJzDjHfsToqP6FrjkeXB1cccd9UwigG48cl6rw8YLl2bEBt5EG5BLbtrU1v4XPHeiCYnkbFCEVL4NM8MyTuESTXdfgnJvVpipYFTy3bqQj/2I3l84WWOh7ank+VtTblNXBjJXEVcOaHlLmXGqlN7jOC9cY07+fAGbB5xJCgN2fLJL5zlaW3+catf/LuX7RA0cG1vBCSmZHV6xlnbbaS8/rnbaqfh1gF1NlRaD/lzySibM9qhhmJI0adJUdW+gus6d1U1mX+u6X1sMi4+Jx0ka+EKrhR21gaCfKv9rXhEJMpr7bys/np7cCW7IDTdUuR2tnV1c0CftuDOrn9fnFCeQzs5gsUtERg6ymSz6QyNHXQUSRfI8W49LqsNH1TkH80HPwJjH2hAzcjB0aR6wEmM89xmFO1F+CIF26b5kM0y5c4CwxUUWyKsBwAiTtRLWa4py3NbH8lLWW7n2qZ6KzVWLS4uAGRfJlaGC+sD74o6qItD4=
after_deploy:
  - bash worker/after_deploy.sh
env:
  global:
  - secure: zbVjEhh/E4Yp3Fmd4+4SAVhoLE4ht6Q8/9VAjzgYSXneCuJHgzLWBlZ4u6ERHTjChqqMyI/r7Bs5hP7EVl2M8Z6cfcHdSyednIswge1f3sR4pUwJpQnhlOHrzjkGJG3C1C2gptHDxAWW/gxnvPtQ67nUTPaYqXgm2m92l6W39xP1cWrJuHWEYFiFZEASk1rGwOu+H+zDOdvFxGJmoK0gTWUOnHITD6wB68lcgck8U0dJY0WdksEA2qKioT2f2JLkZrIkwaOgy16DLQ30XuXHYyAtP0ZFGVxPiV460Q01aDqpwEVPxfHuoH+yak/HI0XJ20zaudduhW8Wgmdh/djhVwhoUqt8TB9IX2QLsHF5RgRMHuLFkJWwRa2xdMElOI3BgPCiGXGIssLp+wr0JDPUEdK6fGqnAbNEO9UjcjjPZvO9tQkp9raZ12joOyvxUpb0uq5JpMA4/4uwarDkk5TLiHyAzFb0zNZukXwvgzqrszYICdzXTZG9aQL+/D+VW1JHk6TpqKz60zDuqySbO5SrNqFjKvWHMU+nJP2A4m/NCZELxhJ5vk+0Ut7/Y6qCwl1C19iB7aDwXJ/ZMsogC16eil7qcwydcrZSoCheFOLdqFyAaEG9Zpl/ZfCHBdX/EWxMPbQVkxWN8D3I9MGyMA0CRIbzDueS+1RlscG1/Bg/6LE=
  - secure: EthD2ijr2iKw+9isDzsnBOlpB6KoI7hIm8BDegkVb/cHqtGo+/y+xiKRDpg1Ssi+1PPiicWvkQVDRRqAeRriM0aKH9Ka46hpDAjH/Xa3QYfOj1kXy+/FpwdIVfiCkZeEtvHh9/iubCT+w3p1i/CopiozOQWYwnTmzX1yxXKeGYQqggUer0Ek82vm0bP/jMNcE4exuMJdQamOVPV7iVKnfax9w7btmObh4WSuDolqLWIghale53A95UmNJtiKYl0JwuiQ3/i2vM1UpzhpOdK1kk/HA+0QRdYKesKxf0xp62mX6rt3c1Gx92G/hEs68eE2YWuxaWQL2Oo/yPn+o2PAQUF3RwLh3ci4cKVInDJmfpmYINcE4Dfmy4yiufiHdPUo1pHYwKiespE/fVyGTuMXutwzy41GX0RHw/d4RFm6LoybDcyB4f9/dJW/swBTStpKUbPwjwE3VvzAlsh7dvjDPud2lqjCmzF2hyQpLT2znp8T+1RSoAC9RldDQJJYvAtQ/oi9H7yc3bF6mp8Hh2gZ4gKShs/AjZVRScGf0EKduVqOQa8LEqUYTNVC8i9kLQGCDZ6Ul3N/aw+bM4fzw6q6UQaCKZwxH2sXK2EYBJjJKiTu4bsBu0kcQCH8RpqUaF10pJIS8Oi1e8E7NnJ+b/owk5kR5/UOA1ol2CH/DWkoGnU=
