language: python
python:
  - '3.6'
install:
  - pip install -r requirements/test.txt
  - pip install -e cdi-linking
  - pip install -e linking_ext
script:
  - pytest cdi-linking/test
  - pip install wheel
#after_script: cd ~

#after_success:
#- coveralls

deploy:
  provider: pypi
  user: novavic
  server: https://test.pypi.org/legacy/
  distributions: "bdist_wheel"
  dist: "python"
  package_glob: "dist/*.whl"
  password:
    secure: YxQNqaSjDW5F0fa+yymSGMEaN7avlh4X4nyH6glPNxpQVOtW4UQUMdQ+TAc2qAoXaFTp2uMcGubSaxeZzEkzCd2Orj5s9mTHBGlgWl47a7oM6zI1MSkCl0yzXBszLWs7IbAjhb6/0dHxH5aqbWFdk5LkvnE//p99DUYL2GPlkhJUHKa/ER7W0W4Xv97AXWfJzDjHfsToqP6FrjkeXB1cccd9UwigG48cl6rw8YLl2bEBt5EG5BLbtrU1v4XPHeiCYnkbFCEVL4NM8MyTuESTXdfgnJvVpipYFTy3bqQj/2I3l84WWOh7ank+VtTblNXBjJXEVcOaHlLmXGqlN7jOC9cY07+fAGbB5xJCgN2fLJL5zlaW3+catf/LuX7RA0cG1vBCSmZHV6xlnbbaS8/rnbaqfh1gF1NlRaD/lzySibM9qhhmJI0adJUdW+gus6d1U1mX+u6X1sMi4+Jx0ka+EKrhR21gaCfKv9rXhEJMpr7bys/np7cCW7IDTdUuR2tnV1c0CftuDOrn9fnFCeQzs5gsUtERg6ymSz6QyNHXQUSRfI8W49LqsNH1TkH80HPwJjH2hAzcjB0aR6wEmM89xmFO1F+CIF26b5kM0y5c4CwxUUWyKsBwAiTtRLWa4py3NbH8lLWW7n2qZ6KzVWLS4uAGRfJlaGC+sD74o6qItD4=
