version: "2"
services:
   redis:
      image: redis:latest
   #merged celery with web so that the same start-dev file works for both
   #docker-compose based containerization as well as Kubernetes based containerization
   web:
     #restart: always
     build:
       context: .
       dockerfile: ./web/linkage/compose/django/Dockerfile-dev

     ports:
          - "8002:8000"
     env_file: ./web/linkage/config/settings/.env

     depends_on:
         - postgres2
         - redis
     #environment:
     #        IN_DOCKER: 1
     #user: django
     #use of this volume mount depends on how do we want to manage uploading/copying files
     #to be de-duplicated and linked
     #if we use it then we have to uncomment the "files" line in the bottom most volumes specific#in this file
     #need to check that it is not buggy
     volumes:
         - ./files/:/user_data

     command:
         #for testing
         #sh -c 'echo \"hello\" > /linkage/media/sk_test.csv' &&
         #python manage.py runserver  0.0.0.0:8000
         /bin/bash start-dev.sh
         #for testing
         #  #bash -c "while ! /usr/local/bin/nc -w 1 -z postgres 5452; do sleep 0.1; done; ./manage.py migrate; while :; do ./manage.py runserver_plus 0.0.0.0:8000; sleep 1; done"

   postgres2:
      #restart: always
      image: postgres:9.6-alpine
      #env_file: ./web/linkage/config/settings/.env
      ##if we do not want to lose data when the database container is gone
      #volumes:
      #    - db_linking:/var/lib/postgresql/data
      #env_file: env
      #exposing host post 5432 (LHS) to postgres container called "postgres2"'s
      #port 5432 (RHS)
      ports:
        - "5432:5432"
volumes:
    files:
#    db_linking:
