version: 2.0 # use CircleCI 2.0
  jobs: # a collection of steps
    build:
       working_directory: ~/circleci-demo-ligo-lib
       docker: # run the steps with Docker
         - image: circleci/python:3.6 # ...with this image as the primary container; this is where all `steps` will run
       steps: # a collection of executable commands
         -checkout
         - run: # install and activate virtual environment with pip
           command: |           
             pip install -r requirements/base.txt
             pip install -r requirements/test.txt